# Generated by Django 4.2.5 on 2023-09-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('credits', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('photo', models.CharField(max_length=500)),
            ],
        ),
    ]
