# Generated by Django 4.2.5 on 2023-09-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photography',
            name='category',
            field=models.CharField(choices=[('NEBULA', 'Nebula'), ('START', 'Star'), ('GALAXY', 'Galaxy'), ('PLANET', 'Planet')], default='', max_length=100),
        ),
    ]
